# Generated by Django 5.1.6 on 2025-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
