# Generated by Django 5.1.6 on 2025-03-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_rename_imagen_empleado_imagen'),
    ]

    operations = [
    ]
